### ISSUE TITLE
`strategy.fail-fast` fails validation

### ISSUE THREAD

**Issue by mislav** [ericsciple/actions-yaml#25]
This file fails validation:
```yaml
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
```

The error is:
```
build.yml (Line: 4, Col: 18) Unexpected value ''
```
