### ISSUE TITLE
constant false interpreted as NullToken

### ISSUE THREAD

**Issue by rethab** [ericsciple/actions-yaml#27]
Hi, a workflow like the following leads to errors, because of the condition shown below.

```yaml
on:
  workflow_call:
    inputs:
      my-value:
        type: boolean
        default: false
```

The problem is that the following condition is true for `false` and therefore the `default: false` is turned into a `NullToken`

https://github.com/ericsciple/actions-yaml/blob/fa13d9f8c14e685c96f0697b703461290727a648/workflows/yaml-object-reader.ts#L114-L116

On another note: @ericsciple are you planning on continuing work on this? I might be -- please let me know :)
